-- [이 파일이 왜 필요한가]
-- 이 앱이 쓰는 테이블 3개를 만드는 SQL. Flyway가 앱 시작 시 이 파일을 실행해서 DB 구조를 맞춰줌.
--
-- [왜 SQL을 직접 쓰나]
-- 예전에는 Hibernate가 엔티티 클래스를 보고 알아서 테이블을 만들었음(ddl-auto: update).
-- 그런데 그 방식은 컬럼을 "추가"만 하고 삭제/이름변경은 못 함. 그래서 엔티티에서 필드를 지워도
-- DB에는 컬럼이 그대로 남고, 필드 이름을 바꾸면 옛 컬럼은 남은 채 새 컬럼이 하나 더 생김
-- (데이터는 옛 컬럼에 있는데 앱은 빈 새 컬럼을 읽는 상태가 조용히 만들어짐).
-- Flyway를 쓰면 어떤 SQL이 실행될지 파일로 미리 확정되고, 적용 이력이 flyway_schema_history 테이블에 남음.
--
-- [규칙] 이미 서버에 적용된 마이그레이션 파일은 절대 수정하지 말 것.
-- Flyway가 파일 내용의 체크섬을 기록해두기 때문에, 고치면 다음 실행 때 "파일이 바뀌었다"며 기동을 거부함.
-- 스키마를 바꿔야 하면 V2__xxx.sql 처럼 새 파일을 추가하는 방식으로 진행.
--
-- 이 파일의 내용은 손으로 적은 게 아니라, 기존 엔티티 클래스로부터 Hibernate가 생성한 DDL을 옮긴 것임
-- (jakarta.persistence.schema-generation 옵션 사용). 컬럼명 변환 규칙(sidoSigungu -> sido_sigungu) 등을
-- 사람이 옮겨 적다 틀리는 걸 막기 위함.

-- CCTV 설치 위치
-- 다른 두 테이블과 달리 id에 auto increment가 없음: 원본 공공데이터에 이미 고유 id가 있어서 그 값을 그대로 PK로 씀
create table cctv (
    id       bigint       not null,
    type     varchar(255),
    address  varchar(255),
    detail   varchar(255),
    dong     varchar(255),
    cameras  integer,
    lat      double precision,
    lon      double precision,
    primary key (id)
);

-- 안심(비상)벨 설치 위치
create table safety_bell (
    id              bigint generated by default as identity,
    address         varchar(255),
    dong            varchar(255),
    install_purpose varchar(255),
    manage_org      varchar(255),
    police_linked   boolean,
    lat             double precision,
    lon             double precision,
    primary key (id)
);

-- 교통사고 다발지역
create table traffic_accident_hotspot (
    id                    bigint generated by default as identity,
    management_no         varchar(255),
    accident_year         integer,
    accident_type         varchar(255),
    sido                  varchar(255),
    sigungu               varchar(255),
    sido_sigungu          varchar(255),
    location_name         varchar(255),
    accident_count        integer,
    casualty_count        integer,
    death_count           integer,
    serious_injury_count  integer,
    minor_injury_count    integer,
    reported_injury_count integer,
    lat                   double precision,
    lon                   double precision,
    primary key (id)
);

-- 시도 이름으로 거르는 조회(GET /api/traffic-accidents?sido=대전)를 위한 인덱스
create index idx_traffic_hotspot_sido on traffic_accident_hotspot (sido);
