-- [이 파일이 왜 필요한가]
-- "안전구역"(사용자가 지도 위에 원을 그려 저장하는 영역)을 담을 safe_zone 테이블을 만드는 SQL.
-- 지금까지의 세 테이블(cctv, safety_bell, traffic_accident_hotspot)은 전부 공공데이터를 "읽기만" 하는
-- 테이블이었음. safe_zone은 사용자가 직접 만들고 고치고 지우는 첫 번째 테이블임.
--
-- [규칙] 이미 서버에 적용된 마이그레이션(V1, V2)은 절대 수정하지 말 것. 새 번호(V3)로 파일을 추가함.
--
-- [device_id가 뭔가]
-- 아직 로그인/회원 기능이 없어서 "이 안전구역이 누구 것인지"를 구분할 방법이 없음.
-- 그래서 프론트가 브라우저마다 랜덤 UUID를 하나 만들어 localStorage에 저장해두고,
-- API를 부를 때마다 X-Device-Id 헤더로 그 값을 보내주기로 함. 서버는 그 문자열을 주인 표시로 저장함.
-- 나중에 실제 로그인이 붙으면 이 컬럼을 user_id로 옮기는 마이그레이션(V4)을 추가하면 됨.
--
-- [주의] device_id는 "브라우저를 구분하는 값"일 뿐 "본인 확인"이 아님.
-- 남의 device_id를 알면 그 사람 안전구역을 볼 수 있다는 뜻이라, 민감한 정보는 넣지 말 것.

create table safe_zone (
    id         bigint generated by default as identity, -- safety_bell과 같은 방식(DB가 번호 자동 채번)
    device_id  varchar(100)     not null,               -- 이 구역의 주인 (브라우저가 만든 UUID 문자열)
    name       varchar(50)      not null,               -- 구역 이름 (예: "집 주변", "학교 근처")
    center_lat double precision not null,               -- 원의 중심 위도
    center_lon double precision not null,               -- 원의 중심 경도
    radius_m   integer          not null,               -- 원의 반지름 (미터). 화면 픽셀이 아니라 실제 거리로 저장
    created_at timestamp        not null,               -- 만든 시각
    updated_at timestamp        not null,               -- 마지막으로 고친 시각
    primary key (id)
);

-- 조회는 거의 전부 "이 기기의 안전구역 목록"(where device_id = ?) 형태라서 인덱스를 걸어둠.
-- 인덱스가 없으면 행이 늘어날수록 테이블 전체를 훑게 됨 (traffic_accident_hotspot의 sido 인덱스와 같은 이유).
create index idx_safe_zone_device_id on safe_zone (device_id);
