-- [이 파일이 왜 필요한가]
-- "안전 장소"(사용자가 카카오맵에서 클릭한 좌표 + 주소/상세주소를 저장하는 장소)를 담을 safe_place 테이블을 만드는 SQL.
-- safe_zone(원형 범위)과는 다른 개념: safe_place는 "집", "학교" 같은 하나의 지점에 주소 텍스트까지 붙여 저장해두고,
-- 나중에 검색해서 좌표를 다시 꺼내 쓰거나(안전구역 만들 때 중심좌표로 재사용 등) 하기 위한 용도.
--
-- [규칙] 이미 서버에 적용된 마이그레이션(V1~V3)은 절대 수정하지 말 것. 새 번호(V4)로 파일을 추가함.
--
-- [device_id] safe_zone과 동일한 방식. 로그인이 없어 "이 장소가 누구 것인지"를 브라우저가 만든 UUID로 구분함.
-- 자세한 이유는 V3__create_safe_zone.sql 상단 주석 참고.

create table safe_place (
    id             bigint generated by default as identity,
    device_id      varchar(100)     not null,               -- 이 장소의 주인 (브라우저가 만든 UUID 문자열)
    name           varchar(50)      not null,                -- 장소 이름 (예: "우리집", "회사")
    address        varchar(255)     not null,                -- 카카오맵에서 클릭/검색해 얻은 지번 또는 도로명 주소
    detail_address varchar(100),                             -- 사용자가 직접 입력하는 상세주소 (동/호수 등). 선택값
    lat            double precision not null,                -- 클릭 지점의 위도
    lon            double precision not null,                -- 클릭 지점의 경도
    created_at     timestamp        not null,
    updated_at     timestamp        not null,
    primary key (id)
);

-- 조회는 거의 전부 "이 기기의 안전 장소 목록"(where device_id = ?) 형태라서 인덱스를 걸어둠.
create index idx_safe_place_device_id on safe_place (device_id);

-- 이름/주소로 검색(장소 검색 기능)할 때 쓰는 인덱스.
-- LIKE '%키워드%' 형태(양쪽 와일드카드)는 이 인덱스를 못 타지만, LIKE '키워드%' 형태의 검색이나
-- 다른 쿼리 플래너 최적화에 도움이 될 수 있어 최소한으로 걸어둠. 데이터 양이 몇 안 되는 개인 저장 목록이라
-- 인덱스가 없어도 성능에는 문제 없음(전문 검색이 필요해지면 그때 별도 검색 인덱스로 교체).
create index idx_safe_place_name on safe_place (name);
