-- [이 파일이 왜 필요한가]
-- 부모/자녀 회원가입-로그인 + "부모가 코드를 발급하면 자녀가 그 코드를 입력해야만 연동되고,
-- 연동된 자녀의 위치만 부모가 볼 수 있다"는 기능에 필요한 4개 테이블을 만드는 SQL.
--
-- [규칙] 이미 서버에 적용된 마이그레이션(V1~V5)은 절대 수정하지 말 것. 새 번호(V6)로 파일을 추가함.
--
-- [기존 안전구역/안전장소와의 차이]
-- safe_zone/safe_place는 로그인이 없어 device_id(브라우저 UUID)로 주인을 구분했지만,
-- 이 기능은 "부모/자녀"라는 진짜 계정 구분과 "연동돼야만 볼 수 있다"는 권한 규칙이 필요해서
-- 이번에 처음으로 실제 회원(app_user) 테이블을 둠.

-- 회원 한 명 = 부모 계정 하나 또는 자녀 계정 하나 (role로 구분, 부모/자녀 전용 테이블을 따로 안 둔 이유는
-- 로그인/이메일/비밀번호 처리 로직이 완전히 같기 때문. 역할별로 다른 데이터가 필요해지면 그때 분리)
-- [테이블명이 user가 아니라 app_user인 이유] user는 Postgres 예약어라 테이블명으로 그대로 쓰면 매 쿼리마다
-- 따옴표를 붙여야 해서 자주 실수가 남. 처음부터 app_user로 피해감.
create table app_user (
    id            bigint generated by default as identity,
    email         varchar(255) not null,
    password_hash varchar(255) not null,      -- 원문 비밀번호는 절대 저장하지 않음 (BCrypt 해시만 저장)
    name          varchar(50)  not null,
    role          varchar(10)  not null,       -- 'PARENT' 또는 'CHILD'
    created_at    timestamp    not null,
    updated_at    timestamp    not null,
    primary key (id)
);

-- 로그인은 항상 이메일로 조회하므로 인덱스가 필요하고, 이메일 중복 가입을 DB 차원에서도 막기 위해 unique.
-- [왜 lower(email)이 아니라 그냥 email인가] Postgres는 lower(email) 같은 표현식 인덱스를 지원하지만,
-- 로컬 테스트에 쓰는 H2는 지원하지 않아 마이그레이션 자체가 실패함(둘 다에서 돌아가야 하는 게 원칙).
-- 그래서 대신 애플리케이션에서 가입 시 이메일을 항상 소문자로 저장해서("A@B.com" -> "a@b.com"),
-- 평범한 unique index만으로도 대소문자만 다른 중복 가입을 막음 (AuthController 참고)
create unique index idx_app_user_email on app_user (email);

-- 부모가 발급한 연동 코드. 한 부모가 여러 번 발급할 수 있어서(자녀가 코드 입력을 실패/지연하는 경우 재발급)
-- "코드 1개 = row 1개"로 두고, 쓰였는지(used_at)와 유효기간(expires_at)을 같이 관리함.
create table family_link_code (
    id          bigint generated by default as identity,
    parent_id   bigint       not null references app_user (id),
    code        varchar(6)   not null,          -- 자녀가 입력하는 6자리 숫자 코드
    expires_at  timestamp    not null,           -- 발급 후 10분 뒤로 설정 (오래된 코드가 계속 유효한 걸 막기 위함)
    used_at     timestamp,                       -- 자녀가 실제로 입력에 성공한 시각. null이면 아직 미사용
    created_at  timestamp    not null,
    primary key (id)
);

-- 자녀가 코드를 입력하면 "이 코드 문자열로 유효한(미사용/미만료) row가 있는지"를 조회하므로 code에 인덱스.
create index idx_family_link_code_code on family_link_code (code);
-- "이 부모가 미사용 코드를 몇 개 갖고 있나"(스팸 방지 캡 확인)를 조회하므로 parent_id에도 인덱스.
create index idx_family_link_code_parent_id on family_link_code (parent_id);

-- 코드 입력에 성공하면 만들어지는 실제 연동 관계. 이 테이블에 row가 있어야만
-- 부모가 그 자녀의 위치를 조회할 수 있음(권한 판정의 기준 테이블).
create table family_link (
    id         bigint    generated by default as identity,
    parent_id  bigint    not null references app_user (id),
    child_id   bigint    not null references app_user (id),
    linked_at  timestamp not null,
    primary key (id)
);

-- 같은 부모-자녀 쌍이 중복으로 연동되는 걸 막음(자녀가 같은 부모 코드를 두 번 입력해도 row가 하나만 남게).
create unique index idx_family_link_parent_child on family_link (parent_id, child_id);
-- "이 부모가 연동한 자녀 목록"과 "이 자녀가 이미 이 부모와 연동됐는지"를 각각 조회하므로 양쪽 다 인덱스.
create index idx_family_link_child_id on family_link (child_id);

-- 자녀 위치의 "가장 최근 값 1건"만 저장 (이동 이력을 저장하는 테이블이 아님).
-- child_id를 PK로 둬서 자연스럽게 "자녀 1명당 최신 위치 1행"이 되고, 매번 upsert로 덮어씀.
create table child_location (
    child_id   bigint primary key references app_user (id),
    lat        double precision not null,
    lon        double precision not null,
    updated_at timestamp        not null
);
