-- [이 파일이 왜 필요한가]
-- 지도 위에 좌표 + 아이콘 번호(1~4)로 마커를 저장하는 map_icon 테이블을 만드는 SQL.
--
-- [규칙] 이미 서버에 적용된 마이그레이션(V1~V6)은 절대 수정하지 말 것. 새 번호(V7)로 파일을 추가함.
--
-- [device_id가 없는 이유 - SafeZone/SafePlace와의 차이]
-- SafeZone/SafePlace는 "이 사람만 보는 내 것"이라 주인을 device_id로 구분해야 했음.
-- 이 아이콘은 지도 위에 찍으면 보는 사람 전부에게 공유되는 마커라서(누가 찍었는지 구분할 필요가 없음)
-- 주인 컬럼 없이 좌표/아이콘 번호/생성시각만 저장함.

create table map_icon (
    id          bigint generated by default as identity,
    lat         double precision not null,             -- 마커 위도
    lon         double precision not null,              -- 마커 경도
    icon_number integer          not null,              -- 아이콘 종류 (1~4)
    created_at  timestamp        not null,
    primary key (id)
);
